### ISSUE TITLE
64-bit Support

### ISSUE THREAD

**Issue by ak0815** [appcelerator-modules/ti.charts#3]
Hello,

can not create a build with the SDK 3.5.0.

Log:
Undefined symbols for architecture arm64:
[TRACE] :    "_OBJC_CLASS_$_CPTBarPlot", referenced from:
[TRACE] :        objc-class-ref in libti.charts.a(TiChartsBarPlotProxy.o)
[TRACE] :    "_OBJC_CLASS_$_CPTTheme", referenced from:
[TRACE] :        objc-class-ref in libti.charts.a(TiChartsChart.o)
[TRACE] :    "_CPTDecimalFromDouble", referenced from:
[TRACE] :        -[TiChartsChart refreshPlotSpaces] in libti.charts.a(TiChartsChart.o)
[TRACE] :    "_OBJC_CLASS_$_CPTPieChart", referenced from:
[TRACE] :        objc-class-ref in libti.charts.a(TiChartsPiePlotProxy.o)
[TRACE] :    "_OBJC_CLASS_$_CPTScatterPlot", referenced from:
[TRACE] :        objc-class-ref in libti.charts.a(TiChartsLinePlotProxy.o)
[TRACE] :    "_OBJC_CLASS_$_CPTPlotRange", referenced from:
[TRACE] :        objc-class-ref in libti.charts.a(TiChartsParsers.o)
[TRACE] :    "_OBJC_CLASS_$_CPTPlotSymbol", referenced from:
[TRACE] :        objc-class-ref in libti.charts.a(TiChartsParsers.o)
[TRACE] :    "_OBJC_CLASS_$_CPTFill", referenced from:
[TRACE] :        objc-class-ref in libti.charts.a(TiChartsParsers.o)
[TRACE] :    "_OBJC_CLASS_$_CPTMutableTextStyle", referenced from:
[TRACE] :        objc-class-ref in libti.charts.a(TiChartsParsers.o)
[TRACE] :    "_OBJC_CLASS_$_CPTColor", referenced from:
[TRACE] :        objc-class-ref in libti.charts.a(TiChartsParsers.o)
[TRACE] :    "_OBJC_CLASS_$_CPTGradient", referenced from:
[TRACE] :        objc-class-ref in libti.charts.a(TiChartsParsers.o)
[TRACE] :    "_kCPTPlainBlackTheme", referenced from:
[TRACE] :        -[TiChartsModule THEME_BLACK] in libti.charts.a(TiChartsModule.o)
[TRACE] :    "_CPTDecimalFromInteger", referenced from:
[TRACE] :        +[TiChartsParsers parseAxis:properties:usingPlotSpace:def:] in libti.charts.a(TiChartsParsers.o)
[TRACE] :    "_OBJC_CLASS_$_CPTMutableLineStyle", referenced from:
[TRACE] :        objc-class-ref in libti.charts.a(TiChartsParsers.o)
[TRACE] :    "_OBJC_CLASS_$_CPTGraphHostingView", referenced from:
[TRACE] :        objc-class-ref in libti.charts.a(TiChartsChart.o)
[TRACE] :    "_OBJC_CLASS_$_CPTXYAxis", referenced from:
[TRACE] :        objc-class-ref in libti.charts.a(TiChartsParsers.o)
[TRACE] :    "_CPTDecimalFromFloat", referenced from:
[TRACE] :        +[TiChartsParsers parsePlotRange:def:] in libti.charts.a(TiChartsParsers.o)
[TRACE] :        +[TiChartsParsers parseAxis:properties:usingPlotSpace:def:] in libti.charts.a(TiChartsParsers.o)
[TRACE] :        +[TiChartsParsers decimalFromFloat:def:] in libti.charts.a(TiChartsParsers.o)
[TRACE] :    "_kCPTStocksTheme", referenced from:
[TRACE] :        -[TiChartsModule THEME_STOCKS] in libti.charts.a(TiChartsModule.o)
[TRACE] :    "_kCPTSlateTheme", referenced from:
[TRACE] :        -[TiChartsModule THEME_SLATE] in libti.charts.a(TiChartsModule.o)
[TRACE] :    "_OBJC_CLASS_$_CPTXYGraph", referenced from:
[TRACE] :        objc-class-ref in libti.charts.a(TiChartsChart.o)
[TRACE] :    "_kCPTPlainWhiteTheme", referenced from:
[TRACE] :        -[TiChartsModule THEME_WHITE] in libti.charts.a(TiChartsModule.o)
[TRACE] :    "_OBJC_CLASS_$_CPTConstraints", referenced from:
[TRACE] :        objc-class-ref in libti.charts.a(TiChartsParsers.o)
[TRACE] :    "_kCPTDarkGradientTheme", referenced from:
[TRACE] :        -[TiChartsModule THEME_DARK_GRADIENT] in libti.charts.a(TiChartsModule.o)
[TRACE] :        -[TiChartsChart configureTheme:] in libti.charts.a(TiChartsChart.o)
[TRACE] :  ld: symbol(s) not found for architecture arm64
[TRACE] :  clang: error: linker command failed with exit code 1 (use -v to see invocation)
[ERROR] :  ** BUILD FAILED **
[ERROR] :  The following build commands failed:
[ERROR] :  	Ld build/FHEM\ APP.build/Release-iphoneos/Test\ APP-universal.build/Objects-normal/arm64/FHEM\ APP normal arm64
[ERROR] :  (1 failure)

BG Andy

**Comment by morinel** [comment]
I have the same problem. Maybe related to the fact that the bundled libCorePlot-CocoaTouch.a doesnot contain a 64 bit architecture?

$ file libCorePlot-CocoaTouch.a 
libCorePlot-CocoaTouch.a: Mach-O universal binary with 3 architectures
libCorePlot-CocoaTouch.a (for architecture armv6):	current ar archive random library
libCorePlot-CocoaTouch.a (for architecture armv7):	current ar archive random library
libCorePlot-CocoaTouch.a (for architecture i386):	current ar archive random library

What version of CorePlot is used for this module? Current CorePlot 2.0 is not compatible and requires more changes to the ti.charts source code.

**Comment by morinel** [comment]
I added a comment to TIMOB-18092

**Comment by ak0815** [comment]
Change the file libCorePlot-CocoaTouch.a against the file from:

https://code.google.com/p/core-plot/

then it works :-)

**Comment by morinel** [comment]
But the file in CorePlot_1.4/Binaries/iOS/libCorePlot-CocoaTouch.a does not contain the x86_64 architecture and hence cannot be used when running on the iOS Simulator. It has the same architectures as stated in my first comment.

Or am I missing something?

**Comment by ak0815** [comment]
For me it works with the simulator.

**Comment by jonalter** [comment]
Closing.
Resolved by #4 via #5
